/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.BorderFactory;



/**
 *
 * @author thoma
 */
public class Login extends javax.swing.JPanel {

    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel_Titulo1 = new javax.swing.JLabel();
        jLabel_usuario1 = new javax.swing.JLabel();
        jTextField_usuario1 = new javax.swing.JTextField();
        jSeparator_usuario1 = new javax.swing.JSeparator();
        jLabel_contraseña1 = new javax.swing.JLabel();
        jPasswordField_contraseña1 = new javax.swing.JPasswordField();
        jSeparator_contraseña1 = new javax.swing.JSeparator();
        jPanel_entrar1 = new javax.swing.JPanel();
        jLabel_Acceder1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        login.setBackground(new java.awt.Color(51, 51, 51));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo1.setText("INICIAR SESIÓN");
        login.add(jLabel_Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 102, -1, -1));

        jLabel_usuario1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_usuario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_usuario1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuario1.setText("USUARIO");
        login.add(jLabel_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 145, -1, -1));

        jTextField_usuario1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_usuario1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_usuario1.setBorder(null);
        jTextField_usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usuario1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_usuario1MouseEntered(evt);
            }
        });
        jTextField_usuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usuario1KeyPressed(evt);
            }
        });
        login.add(jTextField_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 270, 20));
        login.add(jSeparator_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 270, 10));

        jLabel_contraseña1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_contraseña1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_contraseña1.setText("CONTRASEÑA");
        login.add(jLabel_contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 203, -1, -1));

        jPasswordField_contraseña1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField_contraseña1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField_contraseña1.setText("************");
        jPasswordField_contraseña1.setBorder(null);
        jPasswordField_contraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_contraseña1MouseClicked(evt);
            }
        });
        jPasswordField_contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contraseña1ActionPerformed(evt);
            }
        });
        jPasswordField_contraseña1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_contraseña1KeyPressed(evt);
            }
        });
        login.add(jPasswordField_contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 229, 270, -1));
        login.add(jSeparator_contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 245, 270, 10));

        jPanel_entrar1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_Acceder1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Acceder1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Acceder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Acceder1.setText("Acceder");
        jLabel_Acceder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Acceder1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_entrar1Layout = new javax.swing.GroupLayout(jPanel_entrar1);
        jPanel_entrar1.setLayout(jPanel_entrar1Layout);
        jPanel_entrar1Layout.setHorizontalGroup(
            jPanel_entrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Acceder1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel_entrar1Layout.setVerticalGroup(
            jPanel_entrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Acceder1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        login.add(jPanel_entrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 261, -1, -1));

        jButton1.setText("ADMIN");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        login.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuario1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuario1MouseClicked

    private void jTextField_usuario1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuario1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuario1MouseEntered

    private void jTextField_usuario1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usuario1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuario1KeyPressed

    private void jPasswordField_contraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_contraseña1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraseña1MouseClicked

    private void jPasswordField_contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraseña1ActionPerformed

    private void jPasswordField_contraseña1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_contraseña1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraseña1KeyPressed

    private void jLabel_Acceder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Acceder1MouseClicked

        /*
        Menu_vendedor menu_admin = new Menu_vendedor();
        menu_admin.setSize(660, 460);
        menu_admin.setLocation(0,0);

        login.removeAll();
        login.add(menu_admin,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        login.revalidate();
        login.repaint();
        */
    }//GEN-LAST:event_jLabel_Acceder1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        /*
        Menu_administrador menu = new Menu_administrador();
        menu.setSize(660, 460);
        menu.setLocation(0,0);

        login.removeAll();
        login.add(menu,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        login.revalidate();
        login.repaint();
        */
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Acceder1;
    private javax.swing.JLabel jLabel_Titulo1;
    private javax.swing.JLabel jLabel_contraseña1;
    private javax.swing.JLabel jLabel_usuario1;
    private javax.swing.JPanel jPanel_entrar1;
    private javax.swing.JPasswordField jPasswordField_contraseña1;
    private javax.swing.JSeparator jSeparator_contraseña1;
    private javax.swing.JSeparator jSeparator_usuario1;
    private javax.swing.JTextField jTextField_usuario1;
    private javax.swing.JPanel login;
    // End of variables declaration//GEN-END:variables
}
