/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thoma
 */
public class Menu_admin extends javax.swing.JFrame {

    private DefaultTableModel model;
    public Menu_admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        model = tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        titulo_texto = new javax.swing.JLabel();
        rut_texto = new javax.swing.JLabel();
        rut_input = new javax.swing.JTextField();
        rut_separador = new javax.swing.JSeparator();
        buscar_botton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        barraTareas_menu = new javax.swing.JMenuBar();
        personas_menu = new javax.swing.JMenu();
        usuarios_menu = new javax.swing.JMenuItem();
        vendedores_menu = new javax.swing.JMenuItem();
        desarrolladores_menu = new javax.swing.JMenuItem();
        videojuegos_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menu.setBackground(new java.awt.Color(51, 51, 51));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_texto.setBackground(new java.awt.Color(255, 255, 255));
        titulo_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_texto.setForeground(new java.awt.Color(255, 255, 255));
        titulo_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_texto.setText("Menu Administrador");
        menu.add(titulo_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 200, -1));

        rut_texto.setBackground(new java.awt.Color(255, 255, 255));
        rut_texto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rut_texto.setForeground(new java.awt.Color(255, 255, 255));
        rut_texto.setText("Rut:");
        menu.add(rut_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        rut_input.setBackground(new java.awt.Color(51, 51, 51));
        rut_input.setForeground(new java.awt.Color(102, 102, 102));
        rut_input.setBorder(null);
        menu.add(rut_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 270, 20));
        menu.add(rut_separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 270, 10));

        buscar_botton.setText("Buscar");
        menu.add(buscar_botton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "Direccion", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        menu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 180));

        jButton1.setText("jButton1");
        menu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jButton2.setText("jButton2");
        menu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        personas_menu.setText("Personas");

        usuarios_menu.setText("Usuarios");
        usuarios_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarios_menuActionPerformed(evt);
            }
        });
        personas_menu.add(usuarios_menu);

        vendedores_menu.setText("Vendedor");
        personas_menu.add(vendedores_menu);

        desarrolladores_menu.setText("Desarrolladores");
        personas_menu.add(desarrolladores_menu);

        barraTareas_menu.add(personas_menu);

        videojuegos_menu.setText("Videojuegos");
        barraTareas_menu.add(videojuegos_menu);

        setJMenuBar(barraTareas_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarios_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarios_menuActionPerformed
        List <String[]> matriz = Visualizador.sistema.obtenerUsuarios();
        for(int i = 0;i<matriz.size();i++){
            model.addRow(matriz.get(i));
        }
    }//GEN-LAST:event_usuarios_menuActionPerformed
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraTareas_menu;
    private javax.swing.JButton buscar_botton;
    private javax.swing.JMenuItem desarrolladores_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menu;
    private javax.swing.JMenu personas_menu;
    private javax.swing.JTextField rut_input;
    private javax.swing.JSeparator rut_separador;
    private javax.swing.JLabel rut_texto;
    private javax.swing.JLabel titulo_texto;
    private javax.swing.JMenuItem usuarios_menu;
    private javax.swing.JMenuItem vendedores_menu;
    private javax.swing.JMenu videojuegos_menu;
    // End of variables declaration//GEN-END:variables
}
