/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;

/**
 *
 * @author thoma
 */
public class Menu_vendedor extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu_vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jPanel_ingresar = new javax.swing.JPanel();
        ingresarArriendo_texto = new javax.swing.JLabel();
        jPanel_actualizar = new javax.swing.JPanel();
        actualizarArriendo_texto = new javax.swing.JLabel();
        jPanel_eliminar = new javax.swing.JPanel();
        eliminarArriendo_texto = new javax.swing.JLabel();
        jPanel_cerrar_sesion = new javax.swing.JPanel();
        cerrarSesion_texto = new javax.swing.JLabel();
        titulo_texto = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(138, 25));
        setMinimumSize(new java.awt.Dimension(138, 25));

        menu.setBackground(new java.awt.Color(51, 51, 51));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_ingresar.setBackground(new java.awt.Color(0, 153, 153));

        ingresarArriendo_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingresarArriendo_texto.setForeground(new java.awt.Color(255, 255, 255));
        ingresarArriendo_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarArriendo_texto.setText("Ingresar Arriendo");
        ingresarArriendo_texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarArriendo_textoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ingresarLayout = new javax.swing.GroupLayout(jPanel_ingresar);
        jPanel_ingresar.setLayout(jPanel_ingresarLayout);
        jPanel_ingresarLayout.setHorizontalGroup(
            jPanel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ingresarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ingresarArriendo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_ingresarLayout.setVerticalGroup(
            jPanel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ingresarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ingresarArriendo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        menu.add(jPanel_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 122, -1, -1));

        jPanel_actualizar.setBackground(new java.awt.Color(0, 153, 153));

        actualizarArriendo_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        actualizarArriendo_texto.setForeground(new java.awt.Color(255, 255, 255));
        actualizarArriendo_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizarArriendo_texto.setText("Actualizar Arriendo");
        actualizarArriendo_texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarArriendo_textoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_actualizarLayout = new javax.swing.GroupLayout(jPanel_actualizar);
        jPanel_actualizar.setLayout(jPanel_actualizarLayout);
        jPanel_actualizarLayout.setHorizontalGroup(
            jPanel_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_actualizarLayout.createSequentialGroup()
                .addComponent(actualizarArriendo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_actualizarLayout.setVerticalGroup(
            jPanel_actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_actualizarLayout.createSequentialGroup()
                .addComponent(actualizarArriendo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menu.add(jPanel_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 212, -1, -1));

        jPanel_eliminar.setBackground(new java.awt.Color(0, 153, 153));

        eliminarArriendo_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminarArriendo_texto.setForeground(new java.awt.Color(255, 255, 255));
        eliminarArriendo_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarArriendo_texto.setText("Eliminar Arriendo");
        eliminarArriendo_texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarArriendo_textoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_eliminarLayout = new javax.swing.GroupLayout(jPanel_eliminar);
        jPanel_eliminar.setLayout(jPanel_eliminarLayout);
        jPanel_eliminarLayout.setHorizontalGroup(
            jPanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_eliminarLayout.createSequentialGroup()
                .addComponent(eliminarArriendo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_eliminarLayout.setVerticalGroup(
            jPanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_eliminarLayout.createSequentialGroup()
                .addComponent(eliminarArriendo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menu.add(jPanel_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 302, -1, -1));

        jPanel_cerrar_sesion.setBackground(new java.awt.Color(204, 0, 0));

        cerrarSesion_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cerrarSesion_texto.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarSesion_texto.setText("Cerrar Sesión");
        cerrarSesion_texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesion_textoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cerrar_sesionLayout = new javax.swing.GroupLayout(jPanel_cerrar_sesion);
        jPanel_cerrar_sesion.setLayout(jPanel_cerrar_sesionLayout);
        jPanel_cerrar_sesionLayout.setHorizontalGroup(
            jPanel_cerrar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cerrar_sesionLayout.createSequentialGroup()
                .addComponent(cerrarSesion_texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel_cerrar_sesionLayout.setVerticalGroup(
            jPanel_cerrar_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSesion_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menu.add(jPanel_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 392, 200, -1));

        titulo_texto.setBackground(new java.awt.Color(255, 255, 255));
        titulo_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_texto.setForeground(new java.awt.Color(255, 255, 255));
        titulo_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_texto.setText("Menu Vendedor");
        menu.add(titulo_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 56, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarArriendo_textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarArriendo_textoMouseClicked
        /*
        IngresarArriendo ingresarArriendo = new IngresarArriendo();
        ingresarArriendo.setSize(660, 460);
        ingresarArriendo.setLocation(0,0);
        
        menu.removeAll();
        menu.add(ingresarArriendo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        menu.revalidate();
        menu.repaint();
        */
    }//GEN-LAST:event_ingresarArriendo_textoMouseClicked

    private void actualizarArriendo_textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarArriendo_textoMouseClicked
        /*
        ActualizarArriendo actualizarArriendo = new ActualizarArriendo();
        actualizarArriendo.setSize(660, 460);
        actualizarArriendo.setLocation(0,0);
        
        menu.removeAll();
        menu.add(actualizarArriendo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        menu.revalidate();
        menu.repaint();
        */
    }//GEN-LAST:event_actualizarArriendo_textoMouseClicked

    private void eliminarArriendo_textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarArriendo_textoMouseClicked
        /*
        EliminarArriendo eliminarArriendo = new EliminarArriendo();
        eliminarArriendo.setSize(660, 460);
        eliminarArriendo.setLocation(0,0);
        
        menu.removeAll();
        menu.add(eliminarArriendo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        menu.revalidate();
        menu.repaint();
        */
    }//GEN-LAST:event_eliminarArriendo_textoMouseClicked

    private void cerrarSesion_textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesion_textoMouseClicked
        Login login = new Login();
        login.setSize(660, 460);
        login.setLocation(0,0);
        
        menu.removeAll();
        menu.add(login,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        menu.revalidate();
        menu.repaint();
        
    }//GEN-LAST:event_cerrarSesion_textoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizarArriendo_texto;
    private javax.swing.JLabel cerrarSesion_texto;
    private javax.swing.JLabel eliminarArriendo_texto;
    private javax.swing.JLabel ingresarArriendo_texto;
    private javax.swing.JPanel jPanel_actualizar;
    private javax.swing.JPanel jPanel_cerrar_sesion;
    private javax.swing.JPanel jPanel_eliminar;
    private javax.swing.JPanel jPanel_ingresar;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel titulo_texto;
    // End of variables declaration//GEN-END:variables
}
